import { User, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@quotation.com',
    name: 'Admin Manager',
    phone: '+212 612345678',
    role: 'ADMIN',
    status: 'active',
    region: 'Casablanca',
    fonction: 'Administrateur Système',
    createdAt: new Date('2024-01-15'),
    avatar: undefined,
  },
  {
    id: '2',
    email: 'ahmed.benali@quotation.com',
    name: 'Ahmed Ben Ali',
    phone: '+212 612345679',
    role: 'RESPONSABLE',
    status: 'active',
    region: 'Rabat',
    fonction: 'Responsable Commercial',
    createdAt: new Date('2024-02-10'),
    avatar: undefined,
  },
  {
    id: '3',
    email: 'fatima.zahra@quotation.com',
    name: 'Fatima Zahra',
    phone: '+212 612345680',
    role: 'VALIDATEUR',
    status: 'active',
    region: 'Fes',
    fonction: 'Validateur Financier',
    createdAt: new Date('2024-03-05'),
    avatar: undefined,
  },
  {
    id: '4',
    email: 'client.marrakech@quotation.com',
    name: 'Mohammed Saidi',
    phone: '+212 612345681',
    role: 'DEMANDEUR',
    status: 'active',
    region: 'Marrakech',
    fonction: 'Directeur Achat',
    createdAt: new Date('2024-04-01'),
    avatar: undefined,
  },
  {
    id: '5',
    email: 'sara.elmir@quotation.com',
    name: 'Sara El Mir',
    phone: '+212 612345682',
    role: 'RESPONSABLE',
    status: 'active',
    region: 'Tangier',
    fonction: 'Chef de Projet',
    createdAt: new Date('2024-03-20'),
    avatar: undefined,
  },
  {
    id: '6',
    email: 'karim.hassan@quotation.com',
    name: 'Karim Hassan',
    phone: '+212 612345683',
    role: 'VALIDATEUR',
    status: 'inactive',
    region: 'Agadir',
    fonction: 'Auditeur',
    createdAt: new Date('2024-02-28'),
    avatar: undefined,
  },
  {
    id: '7',
    email: 'nadia.bouazouli@quotation.com',
    name: 'Nadia Bouazouli',
    phone: '+212 612345684',
    role: 'DEMANDEUR',
    status: 'pending',
    region: 'Sale',
    fonction: 'Manager Approvisionnement',
    createdAt: new Date('2024-05-10'),
    avatar: undefined,
  },
  {
    id: '8',
    email: 'jalal.diouri@quotation.com',
    name: 'Jalal Diouri',
    phone: '+212 612345685',
    role: 'RESPONSABLE',
    status: 'active',
    region: 'Meknes',
    fonction: 'Directeur Commercial',
    createdAt: new Date('2024-04-15'),
    avatar: undefined,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'Nouvelle quotation reçue',
    message: 'Ahmed Ben Ali a soumis une nouvelle demande de quotation',
    type: 'info',
    read: false,
    createdAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: '2',
    userId: '1',
    title: 'Utilisateur en attente',
    message: 'Nadia Bouazouli attend l\'activation de son compte',
    type: 'warning',
    read: false,
    createdAt: new Date(Date.now() - 15 * 60000),
  },
  {
    id: '3',
    userId: '1',
    title: 'Validation complétée',
    message: 'Fatima Zahra a validé 3 quotations',
    type: 'success',
    read: true,
    createdAt: new Date(Date.now() - 60 * 60000),
  },
  {
    id: '4',
    userId: '1',
    title: 'Mise à jour de profil',
    message: 'Sara El Mir a modifié son profil',
    type: 'info',
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60000),
  },
];
